name = "PkgTemplatesShikiPlugin"
uuid = "8989d94b-1623-4fd9-b5bc-7ab28ad8c70f"
version = "0.1.1"
authors = ["Hiroharu Sugawara <hsugawa@gmail.com>"]

[deps]
PkgTemplates = "14b8a8f1-9102-5b29-a752-f990bacb7fe1"
Mustache = "ffc61752-8dc7-55ee-8c37-f3e9cdd09e70"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
julia = "1.8"
PkgTemplates = "0.7"
Mustache = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
